import { WorkCard } from "./WorkCard";

export const Work = () => {
  const dataWork = [
    {
      name: "LIPOVITAN",
      title: "",
      client: "",
      brand: "Lipovitan",
      agency: "Fortune Media",
      productionHouse: "dream media",
      background: "/work/lipovitan.png",
      video: "/video/lipovitan.mp4",
      link: "lipovitan",
      desc: [
        "STORYBOARD DEVELOPMENT",
        "PRE-PRODUCTION",
        "REHEARSAL DAY",
        "TABLETOP",
        "SHOOTING",
        "ART - SET DESIGN",
        "CHOREOGRAPHY",
        "COLOR GRADING",
        "VIDEO EDITING",
        "MOTION GRAPHICS",
        "3D ANIMATION",
        "SOUND MIX & SOUND DESIGN",
        "MUSIC COMPOSE",
      ],
    },
    {
      name: "fanta",
      title: "colorful",
      client: "",
      brand: "fanta",
      agency: "t&a ogivy",
      productionHouse: "dream media",
      background: "/work/fanta.png",
      video: "/video/fanta.mp4",
      link: "fanta",
      desc: [
        "STORYBOARD DEVELOPMENT",
        "PRE-PRODUCTION",
        "CASTING",
        "WARDROBE",
        "PRODUCTION",
        "SHOOTING",
        "ART - SET DESIGN",
        "COLOR GRADING",
        "VIDEO EDITING",
        "MOTION GRAPHICS",
        "3D ANIMATION",
        "SOUND MIX & SOUND DESIGN",
        "MUSIC COMPOSE",
      ],
    },
    {
      name: "surf",
      title: "BREAKING NEWS",
      client: "",
      brand: "surf",
      agency: "t&a ogivy",
      productionHouse: "dream media",
      background: "/work/surf.png",
      video: "/video/surf.mp4",
      link: "surf",
      desc: [
        "STORYBOARD DEVELOPMENT",
        "PRE-PRODUCTION",
        "CASTING",
        "WARDROBE",
        "REHEARSAL DAY",
        "SHOOTING",
        "ART - SET DESIGN",
        "COLOR GRADING",
        "VIDEO EDITING",
        "MOTION GRAPHICS",
        "CGI",
        "3D MODELING",
        "3D ANIMATION",
        "SOUND MIX & SOUND DESIGN",
        "MUSIC COMPOSE",
      ],
    },
    {
      name: "THƯƠNG PHỔI",
      title: "CSR PROJECT",
      client: "astrazeneca",
      brand: "",
      agency: "TBWA",
      productionHouse: "dream media",
      background: "/work/cancer.png",
      video: "/video/lung-cancer.mp4",
      link: "lung-cancer",
      desc: [
        "STORYBOARD DEVELOPMENT",
        "PRE-PRODUCTION",
        "CASTING",
        "WARDROBE",
        "ART - SET DESIGN",
        "COLOR GRADING",
        "VIDEO EDITING",
        "VFX",
        "SOUND MIX & SOUND DESIGN",
        "MUSIC COMPOSE",
      ],
    },

    {
      name: "fanta",
      title: "Lunar new year",
      client: "",
      brand: "fanta",
      agency: "t&a ogivy",
      productionHouse: "dream media",
      background: "/work/fanta-newyear.png",
      video: "/video/fanta-newyear.mp4",
      link: "fanta-newyear",
      desc: [
        "STORYBOARD DEVELOPMENT",
        "PRE-PRODUCTION",
        "CASTING",
        "WARDROBE",
        "PRODUCTION",
        "SHOOTING",
        "ART - SET DESIGN",
        "COLOR GRADING",
        "VIDEO EDITING",
        "MOTION GRAPHICS",
        "SOUND MIX & SOUND DESIGN",
        "MUSIC COMPOSE",
      ],
    },
    {
      name: "BIA SAI GON CHILL",
      title: "VALENTINE",
      client: "sabeco",
      brand: "Bia Sai Gon Chill",
      agency: "T&A Ogilvy",
      productionHouse: "dream media",
      background: "/work/saigon-chill.png",
      video: "",
      link: "saigon-chill",
      desc: ["PRE-PRODUCTION", "ART - SET DESIGN", "SHOOTING", "DI", "RETOUCH"],
    },
  ];

  return (
    <div className="w-full flex flex-col relative">
      {dataWork.map((item, index) => {
        return <WorkCard key={index} item={item} />;
      })}
    </div>
  );
};

export default Work;
